CREATE TABLE ALUNO 
(   
    COD_ALUNO INT NOT NULL PRIMARY KEY,
    NOME VARCHAR(30) NOT NULL,
 	CPF VARCHAR(11),
    DATA_NASCIMENTO DATE NOT NULL,
    EMAIL VARCHAR(30) NOT NULL,
    SENHA VARCHAR(30) NOT NULL,
    SALDO FLOAT
);

CREATE TABLE ALUNO_CURSO
(   
    COD_ALUNO_CURSO INT NOT NULL PRIMARY KEY,
    DATA_COMPRA DATE,
    NOTA_AVALIACAO FLOAT,
    COD_ALUNO INT NOT NULL REFERENCES ALUNO(COD_ALUNO),
    COD_CURSO INT NOT NULL REFERENCES CURSO(COD_CURSO)
);

CREATE TABLE PROFESSOR
(   
    COD_PROFESSOR INT NOT NULL PRIMARY KEY,
    NOME VARCHAR(30) NOT NULL,
    CPF VARCHAR(11),
    DATA_NASCIMENTO DATE NOT NULL,
    EMAIL VARCHAR(30) NOT NULL,
    SENHA VARCHAR(30) NOT NULL,
    SALDO FLOAT
);

CREATE TABLE CURSO
(   
    COD_CURSO INT NOT NULL PRIMARY KEY,
    NOME VARCHAR(60) NOT NULL,
    DESCRICAO VARCHAR(300),
    DURACAO FLOAT,
    PRECO FLOAT,
    NUMERO_MODULOS INT,
    NOTA_AVALIACAO_MEDIA FLOAT,
    NOTA_QUALIDADE FLOAT,
    COD_PROFESSOR INT NOT NULL REFERENCES PROFESSOR(COD_PROFESSOR)
);

CREATE TABLE MODULO
(   
    COD_MODULO INT NOT NULL PRIMARY KEY,
    NOME VARCHAR(100),
    DESCRICAO VARCHAR(300),
    DURACAO INT,
    COD_CURSO INT NOT NULL REFERENCES CURSO(COD_CURSO)
);

CREATE TABLE DISCIPLINA
(   
    COD_DISCIPLINA SERIAL PRIMARY KEY,
    NOME VARCHAR(100),
    DESCRICAO VARCHAR(300),
    COD_MODULO INT NOT NULL REFERENCES MODULO(COD_MODULO),
    COD_PROFESSOR INT NOT NULL REFERENCES PROFESSOR(COD_PROFESSOR)
);

CREATE TABLE PRE_REQUESITO
(   
    COD_PRE_REQUESITO INT NOT NULL PRIMARY KEY,
    COD_MODULO INT NOT NULL REFERENCES MODULO(COD_MODULO)
);

CREATE TABLE VIDEO_AULA
(   
    COD_VIDEO_AULA SERIAL PRIMARY KEY,
    NOME VARCHAR(30) NOT NULL,
    DESCRICAO VARCHAR(300),
    DURACAO FLOAT,
    COD_DISCIPLINA INT NOT NULL REFERENCES DISCIPLINA(COD_DISCIPLINA)
);

CREATE TABLE ALUNO_VIDEO_AULA
(   
    COD_ALUNO_VIDEO_AULA INT NOT NULL PRIMARY KEY,
    TEMPO_ASSISTIDO FLOAT,
    COD_ALUNO INT NOT NULL REFERENCES ALUNO(COD_ALUNO),
    COD_VIDEO_AULA INT NOT NULL REFERENCES VIDEO_AULA(COD_VIDEO_AULA)
);

CREATE TABLE QUESTIONARIO
(   
    COD_QUESTIONARIO INT NOT NULL PRIMARY KEY,
    NOME VARCHAR(30),
    COD_DISCIPLINA INT NOT NULL REFERENCES DISCIPLINA(COD_DISCIPLINA)
);

CREATE TABLE QUESTAO_QUESTIONARIO
(   
    COD_QUESTAO_QUESTIONARIO INT NOT NULL PRIMARY KEY,
    COD_QUESTAO INT NOT NULL REFERENCES QUESTAO(COD_QUESTAO),
    COD_QUESTIONARIO INT NOT NULL REFERENCES QUESTIONARIO(COD_QUESTIONARIO)
);

CREATE TABLE QUESTAO
(   
    COD_QUESTAO INT NOT NULL PRIMARY KEY,
    TEXTO VARCHAR(500),
    COD_DISCIPLINA INT NOT NULL REFERENCES DISCIPLINA(COD_DISCIPLINA)
);

CREATE TABLE QUESTAO_ALUNO
(   
    COD_QUESTAO_ALUNO INT NOT NULL PRIMARY KEY,
    RESPOSTAR_ALUNO VARCHAR(500),
    RESPOSTA_CORRETA BOOLEAN
);